name: grub4dos 内置调用编译测试

on: 
  push:
   branches-ignore: [ "debug*" ]

jobs:

  build1:
    name: build 0.4.5 with gcc-multilib
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: 下载 grub4dos 0.4.5c 版最新源码
      uses: actions/checkout@v2
      with:
        repository: chenall/grub4dos
        ref: master
        path: 0.4.5c
    - name: 开始编译（调用内置组件）
      uses: ./
      with:
        srcDir: "0.4.5c"
        useQemu: 0
  build2:
    name: build 0.4.6a with gcc-multilib
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: 下载 grub4dos 0.4.6a 版最新源码
      uses: actions/checkout@v2
      with:
        repository: chenall/grub4dos
        ref: 0.4.6a
        path: 0.4.6a
    - name: 下载 ipxe 源码
      uses: actions/checkout@v2
      with:
        repository: ipxe/ipxe
        path: 0.4.6a/ipxe
    - name: 开始编译（调用内置组件）
      uses: ./
      with:
        useQemu: 0
        srcDir: "0.4.6a"
  build3:
    name: build efi with gcc-multilib
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: 下载 grub4dos efi 版最新源码
      uses: actions/checkout@v2
      with:
        repository: chenall/grub4dos
        ref: efi
        path: efi
    - name: 开始编译（调用内置组件）
      uses: ./
      with:
        srcDir: "efi"
        useQemu: 0
    - name: 发布
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: 自动编译发布测试
        files: |
          *.7z
          *.zip
  build4:
    name: build efi with qemu
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: 下载 grub4dos efi 版最新源码
      uses: actions/checkout@v2
      with:
        repository: chenall/grub4dos
        ref: efi
        path: efi
    - name: 开始编译（调用内置组件）
      uses: ./
      with:
        srcDir: "efi"
        useQemu: 1